from __future__ import annotations

import argparse
import csv
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from fast_pattern_trader.models import Candle
from scripts.july_r_composite_walkforward import (
    RULES,
    TESTS,
    components,
    discover_symbols,
    find_month_file,
    load_binance,
    resample,
)


def raw_sign(candle: Candle, rule: str) -> int:
    v = components(candle)[rule]
    threshold = TESTS[rule]
    return 1 if v >= threshold else -1 if v <= -threshold else 0


def next_direction(candles: list[Candle], i: int) -> int:
    if i + 1 >= len(candles):
        return 0
    if candles[i + 1].close > candles[i].close:
        return 1
    if candles[i + 1].close < candles[i].close:
        return -1
    return 0


def evaluate_orientation(candles: list[Candle], rule: str, invert: bool) -> tuple[int, int]:
    correct = active = 0
    for i in range(len(candles) - 1):
        s = raw_sign(candles[i], rule)
        if not s:
            continue
        if invert:
            s = -s
        y = next_direction(candles, i)
        if not y:
            continue
        active += 1
        correct += int(s == y)
    return correct, active


def choose_orientations(train_sets: list[list[Candle]]) -> dict[str, int]:
    """Freeze each R's direction using TRAIN only.

    +1 means native sign is treated as LONG and -1 means native sign is
    inverted. Ties keep native orientation. No test-month information is used.
    """
    out: dict[str, int] = {}
    for rule in RULES:
        normal_correct = normal_active = inverse_correct = inverse_active = 0
        for candles in train_sets:
            c, n = evaluate_orientation(candles, rule, False)
            normal_correct += c
            normal_active += n
            c, n = evaluate_orientation(candles, rule, True)
            inverse_correct += c
            inverse_active += n
        normal_acc = normal_correct / normal_active if normal_active else 0.0
        inverse_acc = inverse_correct / inverse_active if inverse_active else 0.0
        out[rule] = 1 if normal_acc >= inverse_acc else -1
        print(
            f"ORIENT {rule}={'NATIVE' if out[rule] == 1 else 'INVERSE'} "
            f"train_normal={normal_acc*100:.2f}% train_inverse={inverse_acc*100:.2f}% "
            f"n={max(normal_active,inverse_active)}"
        )
    return out


def evaluate_chain(
    candles: list[Candle],
    orientations: dict[str, int],
    trigger_rule: str,
    confirmations: tuple[str, ...],
) -> tuple[int, int, int, int]:
    """Evaluate a strict same-direction chain on the TEST month.

    Entry is generated by trigger_rule at t. Each confirmation is checked on
    the following candle(s): confirmation #1 at t+1, #2 at t+2, etc. A trade
    survives only when every required confirmation is active AND maps to the
    same economic direction as the trigger.

    The realized outcome is measured one candle after the FINAL confirmation,
    so the test never uses a candle's future close to form its own signal.
    """
    opportunities = accepted = correct = long_count = short_count = 0
    depth = len(confirmations)
    last_stage = depth

    for entry_i in range(len(candles) - depth - 1):
        trigger_native = raw_sign(candles[entry_i], trigger_rule)
        if not trigger_native:
            continue
        trigger = trigger_native * orientations[trigger_rule]
        opportunities += 1

        ok = True
        for k, rule in enumerate(confirmations, start=1):
            s = raw_sign(candles[entry_i + k], rule)
            if not s or s * orientations[rule] != trigger:
                ok = False
                break

        if not ok:
            continue

        final_i = entry_i + last_stage
        realized = next_direction(candles, final_i)
        if not realized:
            continue
        accepted += 1
        correct += int(realized == trigger)
        long_count += int(trigger == 1)
        short_count += int(trigger == -1)

    return opportunities, accepted, correct, long_count + short_count


def aggregate_sets(
    datasets: list[list[Candle]], orientations: dict[str, int], trigger: str, confirmations: tuple[str, ...]
) -> tuple[int, int, int, int]:
    vals = [0, 0, 0, 0]
    for candles in datasets:
        r = evaluate_chain(candles, orientations, trigger, confirmations)
        vals = [a + b for a, b in zip(vals, r)]
    return tuple(vals)


def acc(correct: int, n: int) -> float:
    return 100.0 * correct / n if n else 0.0


def load_sets(input_dir: Path, symbols: list[str], month: str, tf: int) -> list[list[Candle]]:
    out = []
    for symbol in symbols:
        path = find_month_file(input_dir, symbol, month)
        if not path:
            continue
        candles = resample(load_binance(path), tf)
        if len(candles) > 20:
            out.append(candles)
    return out


def rank_confirmations(
    train_sets: list[list[Candle]], orientations: dict[str, int], trigger: str, candidates: list[str]
) -> list[tuple[str, float, int]]:
    ranked = []
    for rule in candidates:
        correct = active = 0
        for candles in train_sets:
            for i in range(len(candles) - 1):
                s = raw_sign(candles[i], rule)
                y = next_direction(candles, i)
                if not s or not y:
                    continue
                active += 1
                economic = s * orientations[rule]
                correct += int(economic == y)
        ranked.append((rule, acc(correct, active), active))
    return sorted(ranked, key=lambda x: (x[1], x[2]), reverse=True)


def main() -> None:
    ap = argparse.ArgumentParser(description="Walk-forward R1 + inverse/orientation confirmation selection test")
    ap.add_argument("--input-dir", required=True)
    ap.add_argument("--train-month", default="2026-06")
    ap.add_argument("--test-month", default="2026-07")
    ap.add_argument("--symbols", default="ALL")
    ap.add_argument("--timeframes", default="30,60,120,240")
    ap.add_argument("--trigger", default="R1")
    ap.add_argument("--top", type=int, default=8)
    ap.add_argument("--output", default="reports/july_r_confirmation_selection_wf.csv")
    args = ap.parse_args()

    input_dir = Path(args.input_dir)
    tfs = [int(x.strip()) for x in args.timeframes.split(",") if x.strip()]
    if args.symbols.upper() == "ALL":
        symbols = sorted(set(discover_symbols(input_dir, args.train_month)) | set(discover_symbols(input_dir, args.test_month)))
    else:
        symbols = [x.strip().upper() for x in args.symbols.split(",") if x.strip()]

    all_rows: list[dict] = []
    print(
        f"R_SELECT_WF train={args.train_month} test={args.test_month} "
        f"assets={len(symbols)} tfs={','.join(map(str,tfs))} trigger={args.trigger}"
    )

    for tf in tfs:
        train_sets = load_sets(input_dir, symbols, args.train_month, tf)
        test_sets = load_sets(input_dir, symbols, args.test_month, tf)
        if not train_sets or not test_sets:
            continue

        orientations = choose_orientations(train_sets)
        candidates = [r for r in RULES if r != args.trigger]
        ranked = rank_confirmations(train_sets, orientations, args.trigger, candidates)
        selected = [r for r, _, _ in ranked[: max(3, args.top)]]

        print(f"\nTF={tf}m")
        print("TRAIN_RANK " + " ".join(f"{r}:{a:.2f}%/n{n}" for r, a, n in ranked[:args.top]))
        print("STEP SET RESULT_ACC SIGNALS LONG SHORT")

        for depth in range(0, 4):
            if depth == 0:
                confs: tuple[str, ...] = ()
                label = args.trigger
            else:
                confs = tuple(selected[:depth])
                label = args.trigger + "+" + "+".join(confs)
            opportunities, signals, correct, side_count = aggregate_sets(test_sets, orientations, args.trigger, confs)
            # For depth 0, the signal is R1 and outcome is the next candle.
            print(f"D{depth} {label:<18} {acc(correct,signals):6.2f}% {signals:<7} -    -")
            all_rows.append({
                "timeframe_min": tf,
                "depth": depth,
                "trigger": args.trigger,
                "confirmations": ",".join(confs),
                "test_opportunities": opportunities,
                "test_signals": signals,
                "test_correct": correct,
                "test_accuracy_pct": round(acc(correct, signals), 6),
                "selected_orientation": ";".join(f"{r}:{'N' if orientations[r] == 1 else 'I'}" for r in (args.trigger,) + confs),
                "train_ranked": ";".join(f"{r}:{a:.6f}:{n}" for r, a, n in ranked[:args.top]),
            })

        print("ORIENTATION_TEST", " ".join(f"{r}={'N' if orientations[r] == 1 else 'I'}" for r in RULES))

    p = Path(args.output)
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("w", newline="", encoding="utf-8") as f:
        fields = list(all_rows[0].keys()) if all_rows else [
            "timeframe_min", "depth", "trigger", "confirmations", "test_opportunities",
            "test_signals", "test_correct", "test_accuracy_pct", "selected_orientation", "train_ranked"
        ]
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(all_rows)
    print(f"SAVED {p} rows={len(all_rows)}")


if __name__ == "__main__":
    main()
